/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    CommonButtom: typeof import('./../src/components/common/buttom.vue')['default']
    CommonErrorMsg: typeof import('./../src/components/common/errorMsg.vue')['default']
    CommonInput: typeof import('./../src/components/common/input.vue')['default']
    CommonLink: typeof import('./../src/components/common/link.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditor: typeof import('./../src/components/wang/editor.vue')['default']
    'WangEditor.old': typeof import('./../src/components/wang/editor.old.vue')['default']
  }
}
